server:
  port: 8080
  servlet:
    session:
      timeout: 24h
      cookie:
        max-age: 24h
        http-only: true
        same-site: lax

spring:
  application:
    name: packid-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/drive.file
        provider:
          google:
            issuer-uri: https://accounts.google.com

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO


whatsapp:
  enabled: ${WHATSAPP_ENABLED:true}
  apiVersion: ${WHATSAPP_API_VERSION:v22.0}
  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID:962542003618846}
  accessToken: ${WHATSAPP_ACCESS_TOKEN:EAARmzM6P6pIBROH30rulWOVhHDs0CuCNj3UNSuBfSrMZByAEiBK3tppEQEh9tZC3seznHACWjib1LqLgdF3G4m6JnV8dwJYi4sFjWun42MSQnZBZCDO19LQTulSM7Ddw2mk9UhLq5Qiii4eUSTr28xqBff8CBr9iwDqzlXn5fXXmLVCFkj6eQN2Mg0O1O1FMcM2k4P4itCaVmZCWtukCf6prWZAgxfl7W0nRQAcDppj4bsY27X46MFauZAmT5Lp5SHZCsjimnYKYSCZB7XuZCLZA3mJhmI1}
  templateName: ${WHATSAPP_TEMPLATE_NAME:packid02}
  language: ${WHATSAPP_LANGUAGE:pt_BR}

#  enabled: ${WHATSAPP_ENABLED:false}
#  apiVersion: ${WHATSAPP_API_VERSION:v21.0}
#  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID:}
#  accessToken: ${WHATSAPP_ACCESS_TOKEN:}
#  templateName: ${WHATSAPP_TEMPLATE_NAME:packid_encomenda_chegou}
#  language: ${WHATSAPP_LANGUAGE:pt_BR}
#
#  WHATSAPP_ENABLED=true
#  WHATSAPP_PHONE_NUMBER_ID=SEU_PHONE_NUMBER_ID
#  WHATSAPP_ACCESS_TOKEN=SEU_TOKEN
#  WHATSAPP_TEMPLATE_NAME=packid_encomenda_chegou
#  WHATSAPP_LANGUAGE=pt_BR
