export type ProductUnit='UN'|'KG'; export type PaymentMethod='DINHEIRO'|'PIX'|'DEBITO'|'CREDITO'|'OUTRO'; export type FeeType='PERCENT'|'FIXED';
export interface TenantSummary{id:number;name:string;slug:string}
export interface StoreSummary{id:number;name:string;slug:string;theme:StoreTheme}
export interface TenantOption{id:number;name:string;slug:string;defaultStore:StoreSummary}
export interface LoginResponse{token:string|null;refreshToken:string|null;username:string;role:string|null;tenant:TenantSummary|null;store:StoreSummary|null;tenantSelectionRequired:boolean;availableTenants:TenantOption[]}
export interface Product{id:number;barcode:string|null;internalCode:string|null;name:string;unit:ProductUnit;price:number;active:boolean}
export interface ProductRequest{barcode:string|null;internalCode:string|null;name:string;unit:ProductUnit;price:number;active:boolean}
export interface ProductPage{items:Product[];total:number;page:number;size:number;totalPages:number}
export interface BarcodeLookup{foundLocally:boolean;foundExternally:boolean;product:Product|null;barcode:string;suggestedName:string|null;source:string|null}
export interface SaleItemRequest{productId:number;quantity:number;unitPrice:number;discount:boolean}
export interface SaleServiceRequest{serviceTypeId:number;reference:string|null;baseAmount:number;paymentTypeId:number}
export interface SalePaymentRequest{paymentMethod:PaymentMethod;paymentTypeId:number|null;amount:number;feeType:FeeType;fee:number;amountReceived:number|null}
export interface CreateSaleRequest{items:SaleItemRequest[];services:SaleServiceRequest[];paymentMethod:PaymentMethod|null;amountReceived:number|null;payments:SalePaymentRequest[];receiptMessage:string|null;printReceiptQrCode:boolean;saleControlCustomerId:number|null}
export type UpdateSaleRequest=CreateSaleRequest;
export interface SaleItem{productId:number;barcode:string|null;productName:string;unit:ProductUnit;unitPrice:number;quantity:number;subtotal:number}
export type ControlPaymentStatus='NONE'|'UNPAID'|'PARTIAL'|'PAID';
export interface SaleServiceItem{serviceTypeId:number|null;serviceName:string;reference:string|null;baseAmount:number;serviceFee:number;paymentTypeId:number|null;paymentTypeName:string|null;paymentExtra:number;totalCharged:number}
export interface SalePayment{paymentMethod:PaymentMethod;paymentTypeId:number|null;paymentTypeName:string;amount:number;feeType:FeeType;feeReference:number;fee:number;chargedAmount:number;amountReceived:number|null;changeAmount:number}
export interface Sale{id:number;createdAt:string;operator:string;paymentMethod:PaymentMethod;total:number;feeTotal:number;grandTotal:number;amountReceived:number|null;changeAmount:number;payments:SalePayment[];receiptMessage:string|null;publicReceiptToken:string|null;printReceiptQrCode:boolean;saleControlCustomerId:number|null;saleControlCustomerName:string|null;paidAmount:number;balanceAmount:number;controlPaymentStatus:ControlPaymentStatus;deleted:boolean;deletedAt:string|null;deletedBy:string|null;items:SaleItem[];services:SaleServiceItem[]}
export interface SaleControlCustomer{id:number;name:string;phone:string|null;email:string|null;notes:string|null;active:boolean}
export interface SaleControlCustomerRequest{name:string;phone:string|null;email:string|null;notes:string|null;active:boolean}
export interface SaleControlPayment{id:number;saleId:number;amount:number;paidAt:string;operator:string}
export interface SaleControlSummary{customer:SaleControlCustomer;totalSold:number;totalPaid:number;totalBalance:number;sales:Sale[]}
export interface PublicReceiptStore{name:string;cnpj:string|null;receiptLogoBase64:string|null;receiptLogoContentType:string|null;receiptHeader:string|null;receiptFooter:string|null;receiptPrintLogo:boolean}
export interface PublicReceiptItem{productName:string;unit:ProductUnit;unitPrice:number;quantity:number;subtotal:number}
export interface PublicReceiptServiceItem{serviceName:string;reference:string|null;baseAmount:number;serviceFee:number;paymentTypeName:string|null;paymentExtra:number;totalCharged:number}
export interface PublicReceiptPayment{paymentMethod:PaymentMethod;paymentTypeName:string;cashPayment:boolean;amount:number;fee:number;chargedAmount:number;amountReceived:number|null;changeAmount:number}
export interface PublicReceipt{id:number;createdAt:string;operator:string;paymentMethod:PaymentMethod;total:number;feeTotal:number;grandTotal:number;amountReceived:number|null;changeAmount:number;payments:PublicReceiptPayment[];receiptMessage:string|null;store:PublicReceiptStore;items:PublicReceiptItem[];services:PublicReceiptServiceItem[]}
export type ReportPeriod='DAY'|'MONTH'|'YEAR'; export type ReportMode='SIMPLE_BY_SALE'|'DETAILED_BY_SALE'|'DETAILED_BY_PRODUCT'; export interface ReportPaymentSummary{paymentTypeName:string;amount:number;fee:number;chargedAmount:number} export interface ReportSummary{startDate:string;endDate:string;saleCount:number;total:number;productTotal:number;serviceBaseTotal:number;serviceTariffTotal:number;feeTotal:number;grandTotal:number;averageTicket:number;itemLines:number;payments:ReportPaymentSummary[]} export interface ReportPreviewTable{columns:string[];rows:string[][]} export interface ReportPreview{startDate:string;endDate:string;mode:ReportMode;table:ReportPreviewTable;payments:ReportPaymentSummary[];total:number;productTotal:number;serviceBaseTotal:number;serviceTariffTotal:number;feeTotal:number;grandTotal:number}
export type UserRole='ADMIN'|'MANAGER'|'CASHIER';
export interface AppUser{id:number;userId:number;username:string;googleEmail:string|null;role:UserRole;active:boolean}
export interface AppUserRequest{username:string;password:string|null;googleEmail:string|null;role:UserRole;active:boolean}
export interface QuickProductShortcut{slot:number;product:Product|null;imageBase64:string|null;imageContentType:string|null}
export interface QuickProductShortcutRequest{productId:number|null;imageBase64:string|null;imageContentType:string|null}
export type StoreTheme='HORTIFRUTI'|'LANCHONETE'|'PADARIA'|'PAPELARIA'|'UTENSILIOS'|'DIVERSOS';
export interface PaymentTypeConfig{id:number|null;name:string;legacyMethod:PaymentMethod|null;feePercent:number;feeFixed:number;defaultFeeType:FeeType;defaultPdv:boolean;active:boolean;cashPayment:boolean;displayOrder:number}

export interface ServiceFeeBandConfig{id:number|null;minAmount:number;maxAmount:number|null;feeType:FeeType;feeValue:number}
export interface ServicePaymentExtraConfig{id:number|null;paymentTypeId:number;feeType:FeeType;feeValue:number}
export interface ServiceTypeConfig{id:number|null;name:string;description:string|null;active:boolean;displayOrder:number;feeBands:ServiceFeeBandConfig[];paymentExtras:ServicePaymentExtraConfig[]}
export interface StoreSettings{id:number;name:string;theme:StoreTheme;cnpj:string|null;receiptLogoBase64:string|null;receiptLogoContentType:string|null;receiptHeader:string|null;receiptFooter:string|null;receiptPrintLogo:boolean;receiptDefaultPrintQrCode:boolean;paymentFeeCashPercent:number;paymentFeePixPercent:number;paymentFeeDebitPercent:number;paymentFeeCreditPercent:number;paymentFeeOtherPercent:number;paymentFeeCashFixed:number;paymentFeePixFixed:number;paymentFeeDebitFixed:number;paymentFeeCreditFixed:number;paymentFeeOtherFixed:number;paymentFeeCashDefaultFixed:boolean;paymentFeePixDefaultFixed:boolean;paymentFeeDebitDefaultFixed:boolean;paymentFeeCreditDefaultFixed:boolean;paymentFeeOtherDefaultFixed:boolean;paymentCashDefaultPdv:boolean;paymentPixDefaultPdv:boolean;paymentDebitDefaultPdv:boolean;paymentCreditDefaultPdv:boolean;paymentOtherDefaultPdv:boolean;paymentTypes:PaymentTypeConfig[];serviceTypes:ServiceTypeConfig[]}
export type StoreSettingsRequest=Omit<StoreSettings,'id'>
export interface PlatformTenant{tenantId:number;tenantName:string;tenantSlug:string;storeId:number|null;storeName:string|null;storeSlug:string|null;active:boolean}
export interface TenantProvisionRequest{tenantName:string;tenantSlug:string;storeName:string;adminUsername:string;adminPassword:string;adminGoogleEmail:string|null;theme:StoreTheme;planCode?:string|null;billingCycle?:BillingCycle|null}

export type BillingCycle='MONTHLY'|'ANNUAL';
export type SubscriptionStatus='TRIAL'|'ACTIVE'|'PAST_DUE'|'SUSPENDED'|'CANCELED';
export interface SaasPlan{id:number;code:string;name:string;description:string|null;monthlyPrice:number;annualPrice:number;maxUsers:number;maxPdvs:number;maxStores:number;trialDays:number;graceDays:number;displayOrder:number;active:boolean}
export interface SaasPlanUpdate{name:string;description:string|null;monthlyPrice:number;annualPrice:number;maxUsers:number;maxPdvs:number;maxStores:number;trialDays:number;graceDays:number;displayOrder:number;active:boolean}
export interface SaasUsage{users:number;pdvs:number;stores:number;maxUsers:number;maxPdvs:number;maxStores:number}
export interface SaasSubscription{tenantId:number;tenantName:string;tenantSlug:string;planCode:string;planName:string;status:SubscriptionStatus;effectiveStatus:string;billingCycle:BillingCycle;contractAmount:number;mrr:number;trialEndsAt:string|null;currentPeriodStart:string|null;currentPeriodEnd:string|null;nextDueDate:string|null;notes:string|null;operationalAccess:boolean;usage:SaasUsage}
export interface SaasSubscriptionUpdate{planCode:string;billingCycle:BillingCycle;status:SubscriptionStatus;contractAmount:number|null;trialEndsAt:string|null;currentPeriodStart:string|null;currentPeriodEnd:string|null;nextDueDate:string|null;notes:string|null}
export interface SaasDashboard{totalTenants:number;activeTenants:number;activeSubscriptions:number;trials:number;pastDue:number;suspended:number;canceled:number;activeUsers:number;activePdvs:number;mrr:number;arr:number}
export interface PdvTerminal{id:number;terminalKey:string;name:string;storeId:number;storeName:string;active:boolean;createdAt:string;lastSeenAt:string}
